# CREDIT RISK DATA PREPROCESSING

## Import Relevant Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor

## Loading the Raw Data

In [2]:
raw_csv_data = pd.read_csv("credit_risk_raw.csv")
data = raw_csv_data.copy()

## Data Preprocessing

In [3]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [4]:
data.head()

,loan_id,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
0,LN100000,0.372653,0.013183,0.138870,10000,3149.643450,0.0,10.0,0.500000,6.313200,0.0,4.0,0
1,LN100001,0.277713,0.007620,0.077124,10000,4210.962659,0.0,10.0,8.980004,6.883349,0.0,3.0,0
2,LN100002,0.179291,0.006681,0.032145,10000,2915.160158,1.0,10.0,14.583410,10.945865,0.0,6.0,0
3,LN100003,0.206817,0.009970,0.042773,10000,3884.076941,1.0,10.0,6.894813,NaN,0.0,1.0,1
4,LN100004,0.097129,0.002549,0.009434,10000,712.770666,0.0,10.0,2.592747,8.201624,0.0,1.0,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  5000 non-null   object
 1   annual_income            5000 non-null   float64
 2   monthly_debt             4956 non-null   float64
 3   loan_amount              4948 non-null   float64
 4   total_credit_limit       5000 non-null   int64
 5   credit_used              4943 non-null   float64
 6   total_delinquencies_12m  4952 non-null   float64
 7   open_credit_accounts     4949 non-null   float64
 8   credit_history_years     4934 non-null   float64
 9   oldest_account_age       4956 non-null   float64
 10  late_payments_90d        4947 non-null   float64
 11  hard_inquiries_last_6m   4949 non-null   float64
 12  default                  5000 non-null   int64
dtypes: float64(10), int64(2), object(1)
memory usage: 507.9+ KB

In [6]:
data.describe()

,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
count,5000.000000,4956.000000,4948.000000,5000.0,4943.000000,4952.000000,4949.000000,4934.000000,4956.000000,4947.000000,4949.000000,5000.000000
mean,1368.247787,39.411163,361.420694,10000.0,4504.733834,0.571919,8.102994,6.045472,8.930237,0.311688,1.005594,0.187200
std,8956.781948,275.294882,2551.836975,0.0,1993.583560,0.744072,2.910709,2.996586,3.888720,0.555814,0.995655,0.390111
min,0.013932,0.000083,0.000194,10000.0,0.000000,0.000000,1.814244,0.350454,0.789860,0.000000,0.000000,0.000000
25%,0.175334,0.003948,0.030806,10000.0,3097.227562,0.000000,5.981854,3.903518,6.247738,0.000000,0.000578,0.000000
50%,0.254264,0.006855,0.064347,10000.0,4500.414130,0.012330,10.000000,6.007664,8.867816,0.000000,1.000000,0.000000
75%,0.333069,0.010493,0.110885,10000.0,5855.692157,1.000000,10.000000,8.088857,11.574056,0.987200,1.969803,0.000000
max,60000.000000,3286.449874,32161.974131,10000.0,9863.777118,4.022125,12.154379,16.194382,22.270748,3.997770,6.016353,1.000000

In [7]:
data.isnull().sum()

loan_id                     0
annual_income               0
monthly_debt               44
loan_amount                52
total_credit_limit          0
credit_used                57
total_delinquencies_12m    48
open_credit_accounts       51
credit_history_years       66
oldest_account_age         44
late_payments_90d          53
hard_inquiries_last_6m     51
default                     0
dtype: int64

In [8]:
data['monthly_debt']=data['monthly_debt'].fillna(data['monthly_debt'].median())

In [9]:
data['loan_amount']=data['monthly_debt'].fillna(data['monthly_debt'].median())

In [10]:
data['credit_used']=data['credit_used'].fillna(data['credit_used'].mean())

In [11]:
data['total_delinquencies_12m']=data['total_delinquencies_12m'].fillna(data['total_delinquencies_12m'].median())

In [12]:
data['open_credit_accounts']=data['open_credit_accounts'].fillna(data['open_credit_accounts'].mean())

In [13]:
data['credit_history_years']=data['credit_history_years'].fillna(data['credit_history_years'].mean())

In [14]:
data['oldest_account_age']=data['oldest_account_age'].fillna(data['oldest_account_age'].mean())

In [15]:
data['late_payments_90d']=data['late_payments_90d'].fillna(data['late_payments_90d'].median())

In [16]:
data['hard_inquiries_last_6m']=data['hard_inquiries_last_6m'].fillna(data['hard_inquiries_last_6m'].mean())

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  5000 non-null   object
 1   annual_income            5000 non-null   float64
 2   monthly_debt             5000 non-null   float64
 3   loan_amount              5000 non-null   float64
 4   total_credit_limit       5000 non-null   int64
 5   credit_used              5000 non-null   float64
 6   total_delinquencies_12m  5000 non-null   float64
 7   open_credit_accounts     5000 non-null   float64
 8   credit_history_years     5000 non-null   float64
 9   oldest_account_age       5000 non-null   float64
 10  late_payments_90d        5000 non-null   float64
 11  hard_inquiries_last_6m   5000 non-null   float64
 12  default                  5000 non-null   int64
dtypes: float64(10), int64(2), object(1)
memory usage: 507.9+ KB

In [18]:
data.duplicated().sum()

0

In [19]:
data_without_ID=data.drop(['loan_id'],axis=1)

In [20]:
data_without_ID.head()

,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
0,0.372653,0.013183,0.013183,10000,3149.643450,0.0,10.0,0.500000,6.313200,0.0,4.0,0
1,0.277713,0.007620,0.007620,10000,4210.962659,0.0,10.0,8.980004,6.883349,0.0,3.0,0
2,0.179291,0.006681,0.006681,10000,2915.160158,1.0,10.0,14.583410,10.945865,0.0,6.0,0
3,0.206817,0.009970,0.009970,10000,3884.076941,1.0,10.0,6.894813,8.930237,0.0,1.0,1
4,0.097129,0.002549,0.002549,10000,712.770666,0.0,10.0,2.592747,8.201624,0.0,1.0,0

Multicollinearity Check

In [21]:
data_without_ID.columns.values

array(['annual_income', 'monthly_debt', 'loan_amount',
       'total_credit_limit', 'credit_used', 'total_delinquencies_12m',
       'open_credit_accounts', 'credit_history_years',
       'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m', 'default'], dtype=object)

In [22]:
variables = data_without_ID[['annual_income', 'monthly_debt', 'loan_amount',
       'total_credit_limit', 'credit_used', 'total_delinquencies_12m',
       'open_credit_accounts', 'credit_history_years',
       'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

C:\Users\KINGJOECARES\anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:195: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

In [23]:
vif

                    Feature        VIF
0             annual_income   7.718799
1              monthly_debt        inf
2               loan_amount        inf
3        total_credit_limit  28.304881
4               credit_used   1.003677
5   total_delinquencies_12m   1.115406
6      open_credit_accounts   1.118194
7      credit_history_years   1.002230
8        oldest_account_age   1.003480
9         late_payments_90d   1.004426
10   hard_inquiries_last_6m   1.002768

In [24]:
data_without_ID[['monthly_debt', 'loan_amount']].corr()

              monthly_debt  loan_amount
monthly_debt           1.0          1.0
loan_amount            1.0          1.0

## Features Engineering

In [25]:
data_without_ID["debt_to_income"] = data_without_ID["monthly_debt"] / (data_without_ID["annual_income"] / 12)

In [26]:
data_without_ID["credit_utilization"] = data_without_ID["credit_used"] / data_without_ID["total_credit_limit"]

In [27]:
data_without_ID["loan_to_income"] = data_without_ID["loan_amount"] / data_without_ID["annual_income"]

In [28]:
data_without_ID["delinquencies_last_12m"] = data_without_ID["total_delinquencies_12m"]

In [29]:
data_without_ID["delinquency_ratio"] = data_without_ID["delinquencies_last_12m"] / data_without_ID["open_credit_accounts"]

In [30]:
data_without_ID["utilization_to_income"] = data_without_ID["credit_utilization"] / data_without_ID["annual_income"]

In [31]:
data_without_ID.columns

Index(['annual_income', 'monthly_debt', 'loan_amount', 'total_credit_limit',
       'credit_used', 'total_delinquencies_12m', 'open_credit_accounts',
       'credit_history_years', 'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m', 'default', 'debt_to_income',
       'credit_utilization', 'loan_to_income', 'delinquencies_last_12m',
       'delinquency_ratio', 'utilization_to_income'],
      dtype='object')

In [32]:
data_without_ID=data_without_ID.drop(['annual_income', 'monthly_debt', 'loan_amount', 'total_credit_limit',
       'credit_used', 'total_delinquencies_12m'],axis=1)
data_without_ID.columns

Index(['open_credit_accounts', 'credit_history_years', 'oldest_account_age',
       'late_payments_90d', 'hard_inquiries_last_6m', 'default',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income'],
      dtype='object')

In [33]:
columns_reordered=['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income', 'default']

In [34]:
data_without_ID=data_without_ID[columns_reordered]

In [35]:
data_without_ID.head()

,late_payments_90d,credit_history_years,oldest_account_age,open_credit_accounts,hard_inquiries_last_6m,debt_to_income,credit_utilization,loan_to_income,delinquencies_last_12m,delinquency_ratio,utilization_to_income,default
0,0.0,0.500000,6.313200,10.0,4.0,0.424507,0.314964,0.035376,0.0,0.0,0.845195,0
1,0.0,8.980004,6.883349,10.0,3.0,0.329260,0.421096,0.027438,0.0,0.0,1.516301,0
2,0.0,14.583410,10.945865,10.0,6.0,0.447153,0.291516,0.037263,1.0,0.1,1.625934,0
3,0.0,6.894813,8.930237,10.0,1.0,0.578454,0.388408,0.048205,1.0,0.1,1.878025,1
4,0.0,2.592747,8.201624,10.0,1.0,0.314877,0.071277,0.026240,0.0,0.0,0.733836,0

Multicollinearity Check

In [36]:
variables = data_without_ID[['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

C:\Users\KINGJOECARES\anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:195: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

In [37]:
vif

                   Feature       VIF
0        late_payments_90d  1.300067
1     credit_history_years  4.618566
2       oldest_account_age  5.425185
3     open_credit_accounts  9.506600
4   hard_inquiries_last_6m  1.988244
5           debt_to_income       inf
6       credit_utilization  6.168406
7           loan_to_income       inf
8   delinquencies_last_12m  4.658108
9        delinquency_ratio  5.102905
10   utilization_to_income  1.618016

In [38]:
data_without_ID=data_without_ID.drop(['open_credit_accounts','loan_to_income'],axis=1)

In [39]:
data_without_ID.columns

Index(['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'hard_inquiries_last_6m', 'debt_to_income', 'credit_utilization',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income',
       'default'],
      dtype='object')

In [40]:
variables = data_without_ID[['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'hard_inquiries_last_6m', 'debt_to_income', 'credit_utilization',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

In [41]:
vif

                  Feature       VIF
0       late_payments_90d  1.288147
1    credit_history_years  4.277771
2      oldest_account_age  4.814117
3  hard_inquiries_last_6m  1.954640
4          debt_to_income  4.517558
5      credit_utilization  5.576969
6  delinquencies_last_12m  4.081635
7       delinquency_ratio  3.581439
8   utilization_to_income  1.618005

In [42]:
data_without_ID.head()

,late_payments_90d,credit_history_years,oldest_account_age,hard_inquiries_last_6m,debt_to_income,credit_utilization,delinquencies_last_12m,delinquency_ratio,utilization_to_income,default
0,0.0,0.500000,6.313200,4.0,0.424507,0.314964,0.0,0.0,0.845195,0
1,0.0,8.980004,6.883349,3.0,0.329260,0.421096,0.0,0.0,1.516301,0
2,0.0,14.583410,10.945865,6.0,0.447153,0.291516,1.0,0.1,1.625934,0
3,0.0,6.894813,8.930237,1.0,0.578454,0.388408,1.0,0.1,1.878025,1
4,0.0,2.592747,8.201624,1.0,0.314877,0.071277,0.0,0.0,0.733836,0

In [43]:
data_without_ID.to_csv('preprocessed_data.csv', index=False)