# CREDIT RISK DATA PREPROCESSING

## Import Relevant Libraries

In [46]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor

## Loading the Raw Data

In [47]:
raw_csv_data = pd.read_csv("credit_risk_raw.csv")
data = raw_csv_data.copy()

## Data Preprocessing

In [48]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [49]:
data.head()

,loan_id,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
0,L02511,74637.321234,3195.889125,14195.953941,46825.676414,19230.742442,2,3,2,19,1,5,1
1,L03986,23358.025936,3133.330607,15454.350584,18649.948077,10623.922204,1,5,5,5,0,4,0
2,L00842,78496.389843,842.753657,10757.999031,27201.728228,27201.728228,0,9,18,18,1,5,1
3,L03602,50617.810971,1190.293241,22556.301238,34168.820595,10470.317407,0,6,18,22,0,1,0
4,L03828,74751.205942,2068.677812,18933.117845,36420.744572,25151.119544,1,8,18,18,1,3,0
5,L03924,32768.652818,1700.886109,38826.629146,16953.104447,13515.538646,0,9,15,2,2,5,1
6,L01064,30205.724424,3710.374164,32071.178234,9701.107391,9701.107391,1,10,8,8,0,4,1
7,L03618,59316.898041,2381.209298,9776.371930,45113.061870,37960.442083,1,6,14,23,0,0,0
8,L01058,88454.580385,2620.505691,15239.292847,51101.175486,12323.298457,0,6,3,13,3,0,0
9,L04649,32665.732501,2051.977497,46183.557536,51767.908907,16709.557048,2,11,15,12,1,0,0
10,L04553,82456.487020,2244.660822,38491.913233,41893.838091,29153.183003,0,6,3,22,0,5,0
11,L03528,106358.126763,1969.503343,28251.105462,40946.165131,9054.540249,1,2,14,19,1,1,0
12,L01408,95026.673039,2045.160690,37206.400960,42334.874465,9531.420415,2,6,6,16,3,5,1
13,L03675,63706.227899,1526.156125,19854.790497,13022.492572,NaN,2,4,10,7,1,2,1
14,L00907,37802.877180,1659.093197,13651.700895,60479.931224,22230.380248,1,6,9,3,0,1,0
15,L01861,62313.825171,1139.333781,26213.602543,53689.034710,NaN,3,8,11,5,0,4,1
16,L00199,66164.174369,1122.852559,34914.688891,65286.162880,1000.000000,1,2,8,18,0,5,0
17,L03687,114703.798334,903.092790,31075.323008,37171.122233,36656.790805,0,6,10,9,1,3,0
18,L04367,54487.381320,1541.539406,15867.461853,58395.849159,3946.747186,2,8,19,21,1,2,0
19,L04361,71148.071394,2939.163076,26772.960088,52812.994729,11325.856708,0,11,18,9,0,3,0

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  5100 non-null   object
 1   annual_income            4843 non-null   float64
 2   monthly_debt             4846 non-null   float64
 3   loan_amount              5100 non-null   float64
 4   total_credit_limit       5100 non-null   float64
 5   credit_used              4844 non-null   float64
 6   total_delinquencies_12m  5100 non-null   int64
 7   open_credit_accounts     5100 non-null   int64
 8   credit_history_years     5100 non-null   int64
 9   oldest_account_age       5100 non-null   int64
 10  late_payments_90d        5100 non-null   int64
 11  hard_inquiries_last_6m   5100 non-null   int64
 12  default                  5100 non-null   int64
dtypes: float64(5), int64(7), object(1)
memory usage: 518.1+ KB

In [51]:
data.describe()

,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
count,4843.000000,4846.000000,5100.000000,5100.000000,4844.000000,5100.000000,5100.000000,5100.000000,5100.000000,5100.000000,5100.000000,5100.000000
mean,65265.025391,1801.207265,22201.812810,40316.245050,18855.471701,1.186863,6.538824,10.096667,13.054314,0.806667,2.451373,0.351176
std,19752.864147,791.605539,9763.746429,14895.606714,9118.407512,1.107386,2.847476,5.499904,6.647189,0.905992,1.691026,0.477385
min,20000.000000,200.000000,2000.000000,5000.000000,1000.000000,0.000000,2.000000,1.000000,2.000000,0.000000,0.000000,0.000000
25%,51814.304482,1252.045271,15389.493108,30060.469749,12315.653410,0.000000,4.000000,5.000000,7.000000,0.000000,1.000000,0.000000
50%,65312.366679,1786.883389,22086.468762,40311.224550,18792.578226,1.000000,7.000000,10.000000,13.000000,1.000000,2.000000,0.000000
75%,78418.206937,2346.395199,28764.870042,50569.616381,25140.005495,2.000000,9.000000,15.000000,19.000000,1.000000,4.000000,1.000000
max,143524.754129,4623.244150,56289.104780,107186.263765,51366.860483,7.000000,11.000000,19.000000,24.000000,6.000000,5.000000,1.000000

In [52]:
data.isnull().sum()

loan_id                      0
annual_income              257
monthly_debt               254
loan_amount                  0
total_credit_limit           0
credit_used                256
total_delinquencies_12m      0
open_credit_accounts         0
credit_history_years         0
oldest_account_age           0
late_payments_90d            0
hard_inquiries_last_6m       0
default                      0
dtype: int64

In [53]:
#Removal of duplicates if there is any
data = data.drop_duplicates()

In [54]:
data.duplicated().sum()

0

In [55]:
if data['annual_income'].isnull().sum() > 0: 
    data['annual_income']=data['annual_income'].fillna(data['annual_income'].median())

In [56]:
if data['total_credit_limit'].isnull().sum() > 0: 
    data['total_credit_limit']=data['total_credit_limit'].fillna(data['total_credit_limit'].median())

In [57]:
if data['monthly_debt'].isnull().sum() > 0: 
    data['monthly_debt']=data['monthly_debt'].fillna(data['monthly_debt'].median())

In [58]:
if data['loan_amount'].isnull().sum() > 0: 
    data['loan_amount']=data['loan_amount'].fillna(data['monthly_debt'].median())

In [59]:
if data['credit_used'].isnull().sum() > 0: 
    data['credit_used']=data['credit_used'].fillna(data['credit_used'].mean())

In [60]:
if data['total_delinquencies_12m'].isnull().sum() > 0:
    data['total_delinquencies_12m']=data['total_delinquencies_12m'].fillna(data['total_delinquencies_12m'].median())

In [61]:
if data['open_credit_accounts'].isnull().sum() > 0: 
    data['open_credit_accounts']=data['open_credit_accounts'].fillna(data['open_credit_accounts'].mean())

In [62]:
if data['credit_history_years'].isnull().sum() > 0:
    data['credit_history_years']=data['credit_history_years'].fillna(data['credit_history_years'].mean())

In [63]:
if data['oldest_account_age'].isnull().sum() > 0:
    data['oldest_account_age']=data['oldest_account_age'].fillna(data['oldest_account_age'].mean())

In [64]:
if data['late_payments_90d'].isnull().sum() > 0:
    data['late_payments_90d']=data['late_payments_90d'].fillna(data['late_payments_90d'].median())

In [65]:
if data['hard_inquiries_last_6m'].isnull().sum() > 0:
    data['hard_inquiries_last_6m']=data['hard_inquiries_last_6m'].fillna(data['hard_inquiries_last_6m'].mean())

In [66]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 5099
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  5000 non-null   object
 1   annual_income            5000 non-null   float64
 2   monthly_debt             5000 non-null   float64
 3   loan_amount              5000 non-null   float64
 4   total_credit_limit       5000 non-null   float64
 5   credit_used              5000 non-null   float64
 6   total_delinquencies_12m  5000 non-null   int64
 7   open_credit_accounts     5000 non-null   int64
 8   credit_history_years     5000 non-null   int64
 9   oldest_account_age       5000 non-null   int64
 10  late_payments_90d        5000 non-null   int64
 11  hard_inquiries_last_6m   5000 non-null   int64
 12  default                  5000 non-null   int64
dtypes: float64(5), int64(7), object(1)
memory usage: 546.9+ KB

In [67]:
data_without_ID=data.drop(['loan_id'],axis=1)

In [68]:
data_without_ID.head()

,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
0,74637.321234,3195.889125,14195.953941,46825.676414,19230.742442,2,3,2,19,1,5,1
1,23358.025936,3133.330607,15454.350584,18649.948077,10623.922204,1,5,5,5,0,4,0
2,78496.389843,842.753657,10757.999031,27201.728228,27201.728228,0,9,18,18,1,5,1
3,50617.810971,1190.293241,22556.301238,34168.820595,10470.317407,0,6,18,22,0,1,0
4,74751.205942,2068.677812,18933.117845,36420.744572,25151.119544,1,8,18,18,1,3,0

Multicollinearity Check

In [69]:
data_without_ID.columns.values

array(['annual_income', 'monthly_debt', 'loan_amount',
       'total_credit_limit', 'credit_used', 'total_delinquencies_12m',
       'open_credit_accounts', 'credit_history_years',
       'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m', 'default'], dtype=object)

In [70]:
variables = data_without_ID[['annual_income', 'monthly_debt', 'loan_amount',
       'total_credit_limit', 'credit_used', 'total_delinquencies_12m',
       'open_credit_accounts', 'credit_history_years',
       'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

In [71]:
vif

                    Feature       VIF
0             annual_income  9.699266
1              monthly_debt  5.684646
2               loan_amount  5.579947
3        total_credit_limit  7.544491
4               credit_used  5.312847
5   total_delinquencies_12m  2.110786
6      open_credit_accounts  5.551091
7      credit_history_years  4.090499
8        oldest_account_age  4.496514
9         late_payments_90d  1.763677
10   hard_inquiries_last_6m  2.962906

## Features Engineering

In [72]:
data_without_ID["debt_to_income"] = data_without_ID["monthly_debt"] / (data_without_ID["annual_income"] / 12)

In [73]:
data_without_ID["credit_utilization"] = data_without_ID["credit_used"] / data_without_ID["total_credit_limit"]

In [74]:
data_without_ID["loan_to_income"] = data_without_ID["loan_amount"] / data_without_ID["annual_income"]

In [75]:
data_without_ID["delinquencies_last_12m"] = data_without_ID["total_delinquencies_12m"]

In [76]:
data_without_ID["delinquency_ratio"] = data_without_ID["delinquencies_last_12m"] / data_without_ID["open_credit_accounts"]

In [77]:
data_without_ID["utilization_to_income"] = data_without_ID["credit_utilization"] / data_without_ID["annual_income"]

In [78]:
data_without_ID.columns

Index(['annual_income', 'monthly_debt', 'loan_amount', 'total_credit_limit',
       'credit_used', 'total_delinquencies_12m', 'open_credit_accounts',
       'credit_history_years', 'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m', 'default', 'debt_to_income',
       'credit_utilization', 'loan_to_income', 'delinquencies_last_12m',
       'delinquency_ratio', 'utilization_to_income'],
      dtype='object')

In [79]:
data_without_ID=data_without_ID.drop(['annual_income', 'monthly_debt', 'loan_amount', 'total_credit_limit',
       'credit_used', 'total_delinquencies_12m'],axis=1)
data_without_ID.columns

Index(['open_credit_accounts', 'credit_history_years', 'oldest_account_age',
       'late_payments_90d', 'hard_inquiries_last_6m', 'default',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income'],
      dtype='object')

In [80]:
columns_reordered=['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income', 'default']

In [81]:
data_without_ID=data_without_ID[columns_reordered]

In [82]:
data_without_ID.head()

,late_payments_90d,credit_history_years,oldest_account_age,open_credit_accounts,hard_inquiries_last_6m,debt_to_income,credit_utilization,loan_to_income,delinquencies_last_12m,delinquency_ratio,utilization_to_income,default
0,1,2,19,3,5,0.513827,0.410688,0.190199,2,0.666667,0.000006,1
1,0,5,5,5,4,1.609724,0.569649,0.661629,1,0.200000,0.000024,0
2,1,18,18,9,5,0.128835,1.000000,0.137051,0,0.000000,0.000013,1
3,0,18,22,6,1,0.282184,0.306429,0.445620,0,0.000000,0.000006,0
4,1,18,18,8,3,0.332090,0.690571,0.253282,1,0.125000,0.000009,0

Multicollinearity Check

In [83]:
variables = data_without_ID[['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

In [85]:
vif

                   Feature        VIF
0        late_payments_90d   1.759425
1     credit_history_years   3.905265
2       oldest_account_age   4.235793
3     open_credit_accounts   7.554305
4   hard_inquiries_last_6m   2.871646
5           debt_to_income   4.979018
6       credit_utilization  12.673013
7           loan_to_income   5.130811
8   delinquencies_last_12m   6.683959
9        delinquency_ratio   5.737417
10   utilization_to_income  12.229594

In [86]:
data_without_ID=data_without_ID.drop(['credit_utilization'],axis=1)

In [87]:
data_without_ID.columns

Index(['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m', 'debt_to_income',
       'loan_to_income', 'delinquencies_last_12m', 'delinquency_ratio',
       'utilization_to_income', 'default'],
      dtype='object')

In [88]:
variables = data_without_ID[['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m', 'debt_to_income',
       'loan_to_income', 'delinquencies_last_12m', 'delinquency_ratio',
       'utilization_to_income']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

In [89]:
vif

                  Feature       VIF
0       late_payments_90d  1.750579
1    credit_history_years  3.808740
2      oldest_account_age  4.082393
3    open_credit_accounts  6.836811
4  hard_inquiries_last_6m  2.814663
5          debt_to_income  4.578924
6          loan_to_income  4.638736
7  delinquencies_last_12m  6.644806
8       delinquency_ratio  5.559595
9   utilization_to_income  3.622582

In [90]:
data_without_ID.head()

,late_payments_90d,credit_history_years,oldest_account_age,open_credit_accounts,hard_inquiries_last_6m,debt_to_income,loan_to_income,delinquencies_last_12m,delinquency_ratio,utilization_to_income,default
0,1,2,19,3,5,0.513827,0.190199,2,0.666667,0.000006,1
1,0,5,5,5,4,1.609724,0.661629,1,0.200000,0.000024,0
2,1,18,18,9,5,0.128835,0.137051,0,0.000000,0.000013,1
3,0,18,22,6,1,0.282184,0.445620,0,0.000000,0.000006,0
4,1,18,18,8,3,0.332090,0.253282,1,0.125000,0.000009,0

In [91]:
data_without_ID.to_csv('preprocessed_data.csv', index=False)