# CREDIT RISK DATA PREPROCESSING

## Import Relevant Libraries

In [1]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor

## Loading the Raw Data

In [2]:
raw_csv_data = pd.read_csv("credit_risk_raw.csv")
data = raw_csv_data.copy()

## Data Preprocessing

In [3]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [4]:
data.head()

,loan_id,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
0,LN100000,0.372653,0.013183,0.138870,10000,3149.643450,0.0,10.0,0.500000,6.313200,0.0,4.0,0
1,LN100001,0.277713,0.007620,0.077124,10000,4210.962659,0.0,10.0,8.980004,6.883349,0.0,3.0,0
2,LN100002,0.179291,0.006681,0.032145,10000,2915.160158,1.0,10.0,14.583410,10.945865,0.0,6.0,0
3,LN100003,0.206817,0.009970,0.042773,10000,3884.076941,1.0,10.0,6.894813,NaN,0.0,1.0,1
4,LN100004,0.097129,0.002549,0.009434,10000,712.770666,0.0,10.0,2.592747,8.201624,0.0,1.0,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  5000 non-null   object
 1   annual_income            5000 non-null   float64
 2   monthly_debt             4956 non-null   float64
 3   loan_amount              4948 non-null   float64
 4   total_credit_limit       5000 non-null   int64
 5   credit_used              4943 non-null   float64
 6   total_delinquencies_12m  4952 non-null   float64
 7   open_credit_accounts     4949 non-null   float64
 8   credit_history_years     4934 non-null   float64
 9   oldest_account_age       4956 non-null   float64
 10  late_payments_90d        4947 non-null   float64
 11  hard_inquiries_last_6m   4949 non-null   float64
 12  default                  5000 non-null   int64
dtypes: float64(10), int64(2), object(1)
memory usage: 507.9+ KB

In [6]:
data=data.dropna(axis=0)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4558 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   loan_id                  4558 non-null   object
 1   annual_income            4558 non-null   float64
 2   monthly_debt             4558 non-null   float64
 3   loan_amount              4558 non-null   float64
 4   total_credit_limit       4558 non-null   int64
 5   credit_used              4558 non-null   float64
 6   total_delinquencies_12m  4558 non-null   float64
 7   open_credit_accounts     4558 non-null   float64
 8   credit_history_years     4558 non-null   float64
 9   oldest_account_age       4558 non-null   float64
 10  late_payments_90d        4558 non-null   float64
 11  hard_inquiries_last_6m   4558 non-null   float64
 12  default                  4558 non-null   int64
dtypes: float64(10), int64(2), object(1)
memory usage: 498.5+ KB

In [8]:
data_without_ID=data.drop(['loan_id'],axis=1)

In [9]:
data_without_ID.head()

,annual_income,monthly_debt,loan_amount,total_credit_limit,credit_used,total_delinquencies_12m,open_credit_accounts,credit_history_years,oldest_account_age,late_payments_90d,hard_inquiries_last_6m,default
0,0.372653,0.013183,0.138870,10000,3149.643450,0.0,10.0,0.500000,6.313200,0.0,4.0,0
1,0.277713,0.007620,0.077124,10000,4210.962659,0.0,10.0,8.980004,6.883349,0.0,3.0,0
2,0.179291,0.006681,0.032145,10000,2915.160158,1.0,10.0,14.583410,10.945865,0.0,6.0,0
4,0.097129,0.002549,0.009434,10000,712.770666,0.0,10.0,2.592747,8.201624,0.0,1.0,0
5,0.277803,0.007290,0.077174,10000,4926.587415,0.0,10.0,2.896384,15.043482,0.0,2.0,0

Multicollinearity Check

In [10]:
data_without_ID.columns.values

array(['annual_income', 'monthly_debt', 'loan_amount',
       'total_credit_limit', 'credit_used', 'total_delinquencies_12m',
       'open_credit_accounts', 'credit_history_years',
       'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m', 'default'], dtype=object)

In [11]:
variables = data_without_ID[['annual_income', 'monthly_debt', 'loan_amount',
       'total_credit_limit', 'credit_used', 'total_delinquencies_12m',
       'open_credit_accounts', 'credit_history_years',
       'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

In [12]:
vif

                    Feature        VIF
0             annual_income  13.788679
1              monthly_debt   9.433274
2               loan_amount   6.411781
3        total_credit_limit  27.982844
4               credit_used   1.004673
5   total_delinquencies_12m   1.122909
6      open_credit_accounts   1.124000
7      credit_history_years   1.002302
8        oldest_account_age   1.003904
9         late_payments_90d   1.004191
10   hard_inquiries_last_6m   1.003992

## Features Engineering

In [13]:
data_without_ID["debt_to_income"] = data_without_ID["monthly_debt"] / (data_without_ID["annual_income"] / 12)

In [14]:
data_without_ID["credit_utilization"] = data_without_ID["credit_used"] / data_without_ID["total_credit_limit"]

In [15]:
data_without_ID["loan_to_income"] = data_without_ID["loan_amount"] / data_without_ID["annual_income"]

In [16]:
data_without_ID["delinquencies_last_12m"] = data_without_ID["total_delinquencies_12m"]

In [17]:
data_without_ID["delinquency_ratio"] = data_without_ID["delinquencies_last_12m"] / data_without_ID["open_credit_accounts"]

In [18]:
data_without_ID["utilization_to_income"] = data_without_ID["credit_utilization"] / data_without_ID["annual_income"]

In [19]:
data_without_ID.columns

Index(['annual_income', 'monthly_debt', 'loan_amount', 'total_credit_limit',
       'credit_used', 'total_delinquencies_12m', 'open_credit_accounts',
       'credit_history_years', 'oldest_account_age', 'late_payments_90d',
       'hard_inquiries_last_6m', 'default', 'debt_to_income',
       'credit_utilization', 'loan_to_income', 'delinquencies_last_12m',
       'delinquency_ratio', 'utilization_to_income'],
      dtype='object')

In [20]:
data_without_ID=data_without_ID.drop(['annual_income', 'monthly_debt', 'loan_amount', 'total_credit_limit',
       'credit_used', 'total_delinquencies_12m'],axis=1)
data_without_ID.columns

Index(['open_credit_accounts', 'credit_history_years', 'oldest_account_age',
       'late_payments_90d', 'hard_inquiries_last_6m', 'default',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income'],
      dtype='object')

In [21]:
columns_reordered=['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income', 'default']

In [22]:
data_without_ID=data_without_ID[columns_reordered]

In [23]:
data_without_ID.head()

,late_payments_90d,credit_history_years,oldest_account_age,open_credit_accounts,hard_inquiries_last_6m,debt_to_income,credit_utilization,loan_to_income,delinquencies_last_12m,delinquency_ratio,utilization_to_income,default
0,0.0,0.500000,6.313200,10.0,4.0,0.424507,0.314964,0.372652,0.0,0.0,0.845195,0
1,0.0,8.980004,6.883349,10.0,3.0,0.329260,0.421096,0.277712,0.0,0.0,1.516301,0
2,0.0,14.583410,10.945865,10.0,6.0,0.447153,0.291516,0.179290,1.0,0.1,1.625934,0
4,0.0,2.592747,8.201624,10.0,1.0,0.314877,0.071277,0.097128,0.0,0.0,0.733836,0
5,0.0,2.896384,15.043482,10.0,2.0,0.314879,0.492659,0.277802,0.0,0.0,1.773413,0

Multicollinearity Check

In [24]:
variables = data_without_ID[['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'open_credit_accounts', 'hard_inquiries_last_6m',
       'debt_to_income', 'credit_utilization', 'loan_to_income',
       'delinquencies_last_12m', 'delinquency_ratio', 'utilization_to_income']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

In [25]:
vif

                   Feature        VIF
0        late_payments_90d   1.305218
1     credit_history_years   4.684783
2       oldest_account_age   5.543985
3     open_credit_accounts  10.523536
4   hard_inquiries_last_6m   1.985815
5           debt_to_income   6.024381
6       credit_utilization   6.781043
7           loan_to_income   7.224412
8   delinquencies_last_12m   4.707352
9        delinquency_ratio   5.279426
10   utilization_to_income   2.212783

In [26]:
data_without_ID=data_without_ID.drop('open_credit_accounts',axis=1)

In [27]:
data_without_ID.columns

Index(['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'hard_inquiries_last_6m', 'debt_to_income', 'credit_utilization',
       'loan_to_income', 'delinquencies_last_12m', 'delinquency_ratio',
       'utilization_to_income', 'default'],
      dtype='object')

In [28]:
variables = data_without_ID[['late_payments_90d', 'credit_history_years', 'oldest_account_age',
       'hard_inquiries_last_6m', 'debt_to_income', 'credit_utilization',
       'loan_to_income', 'delinquencies_last_12m', 'delinquency_ratio',
       'utilization_to_income']]

vif = pd.DataFrame()
vif['Feature'] = variables.columns
vif['VIF'] = [variance_inflation_factor(variables.values, i) for i in range(variables.shape[1])]

In [29]:
vif

                  Feature       VIF
0       late_payments_90d  1.299217
1    credit_history_years  4.489476
2      oldest_account_age  5.226359
3  hard_inquiries_last_6m  1.965869
4          debt_to_income  5.292031
5      credit_utilization  6.588760
6          loan_to_income  6.514963
7  delinquencies_last_12m  4.143145
8       delinquency_ratio  3.616962
9   utilization_to_income  2.142683

In [30]:
data_without_ID.to_csv('data_preprocessed.csv', index=False)